name: transborder_logistics
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  get: ^4.6.5
  dio: ^5.1.2
  icons_plus: ^5.0.0
  flutter_svg: ^2.0.2
  connectivity_plus: ^7.0.0
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  share_plus: ^12.0.0
  flutter_native_splash: ^2.2.19
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  photo_view: ^0.15.0
  hugeicons: ^1.1.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_12:
      image: assets/images/slogo.png
      icon_background_color: "#ffffff"
      image_dark: assets/images/slogo.png
      icon_background_color_dark: "#ffffff"